Added Active Storage, Action Text and Google Maps API to application.
BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final pull request #22
Opened 2024-03-13 01:16 UTC by ErikGmz

# Description

What did you implemented/Why did you implemented this:

- Active Storage was installed and tested in the project.
- Action Text was installed and tested in the project.
- Google Maps API was installed and tested in the project.
- Scaffolded test model, controller and views (**_these will be deleted later_**).

Examples:

- Test registration with some images, enriched text and location data.

## Testing

- Run the Rails migrations, rails server command and check /test endpoints.

2024-03-13 01:32 UTC, MauricioNC requested changes

2024-03-13 01:32 UTC, MauricioNC commented on app/javascript/controllers/places_controller.js
> +      */
Don't leave this kind of comments.

2024-03-13 01:32 UTC, MauricioNC commented on app/javascript/controllers/places_controller.js
> +      // when either the latitude or longitude change.
Same here

2024-03-13 01:32 UTC, MauricioNC commented on app/javascript/controllers/places_controller.js
> +      // Load Google Map.
Same here

2024-03-13 01:32 UTC, MauricioNC commented on app/javascript/controllers/places_controller.js
> +      // This also will be used only if Google Cloud Billing is activated).
Same here

2024-03-13 01:32 UTC, MauricioNC commented on config/credentials.yml.enc
> +jz2OPIeRtpylG+Pg66NDMQM67QfkEkdvMRCOGIKl06gDl4bnaY8PnFk7HJjStox5eKkQtruzqegD9C1G7IaG7buqVOfWn2pzUnfxxQ/7S51e52sk/RlZZ3Vjl/ScpZU0gdF5Uf1BnWRjEo1i2vQk01cqvqgTaSMrZc/dPxXcb4HOw1Vv5v/7pR1loRq0uZ220B834+I
This must be ignored!
Add this file to the .gitignore file

2024-03-13 01:32 UTC, MauricioNC commented on app/controllers/tests_controller.rb
> +class TestsController < ApplicationController
Why do you have a test controller?, Is this part of your project?

2024-03-13 01:36 UTC, ErikGmz commented on app/javascript/controllers/places_controller.js
> +      */
Fixed.

2024-03-13 01:36 UTC, MauricioNC commented
You have many changes. Remember that you should do the minimum necessary changes for each PR yo do.

By this PR you are installing Action Text, connecting to the Google Maps API, installing Active Storage, etc. Just focus on one thing at a time.

2024-03-13 01:36 UTC, ErikGmz commented on app/javascript/controllers/places_controller.js
> +      // when either the latitude or longitude change.
Fixed.

2024-03-13 01:38 UTC, ErikGmz commented on config/credentials.yml.enc
> +jz2OPIeRtpylG+Pg66NDMQM67QfkEkdvMRCOGIKl06gDl4bnaY8PnFk7HJjStox5eKkQtruzqegD9C1G7IaG7buqVOfWn2pzUnfxxQ/7S51e52sk/RlZZ3Vjl/ScpZU0gdF5Uf1BnWRjEo1i2vQk01cqvqgTaSMrZc/dPxXcb4HOw1Vv5v/7pR1loRq0uZ220B834+I
Without that file none of the application's API will work. All of the API keys contained in that file are encrypted and the decryption key is already ignored.

2024-03-13 01:41 UTC, MauricioNC commented on config/credentials.yml.enc
> +jz2OPIeRtpylG+Pg66NDMQM67QfkEkdvMRCOGIKl06gDl4bnaY8PnFk7HJjStox5eKkQtruzqegD9C1G7IaG7buqVOfWn2pzUnfxxQ/7S51e52sk/RlZZ3Vjl/ScpZU0gdF5Uf1BnWRjEo1i2vQk01cqvqgTaSMrZc/dPxXcb4HOw1Vv5v/7pR1loRq0uZ220B834+I
This file will be ignored and hidden in the master branch, but you already have it in the local repository.

2024-03-13 01:41 UTC, ErikGmz commented on app/controllers/tests_controller.rb
> +class TestsController < ApplicationController
It was created in order to test the Action Storage, Action Text and Google Maps API features. It's also planned to be removed (along with its model and views) in the future.

2024-03-13 01:44 UTC, MauricioNC commented on config/credentials.yml.enc
> +jz2OPIeRtpylG+Pg66NDMQM67QfkEkdvMRCOGIKl06gDl4bnaY8PnFk7HJjStox5eKkQtruzqegD9C1G7IaG7buqVOfWn2pzUnfxxQ/7S51e52sk/RlZZ3Vjl/ScpZU0gdF5Uf1BnWRjEo1i2vQk01cqvqgTaSMrZc/dPxXcb4HOw1Vv5v/7pR1loRq0uZ220B834+I
Also you will need this credential when you deploy your application. You are storing sensitive information so you must have to ignore it.

2024-03-13 01:57 UTC, MauricioNC approved these changes

2024-03-13 02:02 UTC, ErikGmz commented on config/credentials.yml.enc
> +jz2OPIeRtpylG+Pg66NDMQM67QfkEkdvMRCOGIKl06gDl4bnaY8PnFk7HJjStox5eKkQtruzqegD9C1G7IaG7buqVOfWn2pzUnfxxQ/7S51e52sk/RlZZ3Vjl/ScpZU0gdF5Uf1BnWRjEo1i2vQk01cqvqgTaSMrZc/dPxXcb4HOw1Vv5v/7pR1loRq0uZ220B834+I
Now I get what do you mean; I'm going to address that right now.

2024-03-13 02:09 UTC, ErikGmz commented on app/controllers/tests_controller.rb
> +class TestsController < ApplicationController
You're right. The reason I decided to create a specific scaffold for those features was that I didn't want to rush the planned project's model development.

2024-03-15 00:36 UTC, juperameza approved these changes

2024-03-15 01:33 UTC, AnaCarrizales approved these changes

2024-03-15 01:55 UTC, merged