Property Management For Hosts
BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final pull request #29
Opened 2024-03-16 04:46 UTC by ErikGmz

# Description

- Generated completely functional Accommodations controller and views.  
- Accommodations management with Google Maps API, Active Storage and Action Text features.
- Users creations and additions bugs fixes.
- Tests model, controller and views deletion.

## Testing

- Run the corresponding Rails migrations in order to properly update the local database.
- Ask the team for the application's API credentials and master key files.
- Put the credentials files into the config folder.
- Run the application with either rails server or ./bin/dev commands.
- Navigate to /accommodations route in order to check the corresponding CRUD.

2024-03-16 05:35 UTC, MauricioNC requested changes

2024-03-16 05:35 UTC, MauricioNC commented on app/views/accommodations/_form.html.erb
> +              }) do |form| %>
You are showing your Google API key in the form, this could be a critic security problem. I believe you can find another way to pass this API key

2024-03-18 21:47 UTC, ErikGmz commented on app/views/accommodations/_form.html.erb
> +              }) do |form| %>
It seems that it's very difficult, or impossible, to completely hide the Google Maps key in the client side context, since it also appears in Network requests lists; however, I made the Stimulus controller request it from a special controller instead, preventing it from being printed in the HTML code; moreover, I added user's authentication and IP's checks in order to protect it as best as possible. I hope this was enough to guarantee a basic key's protection.

2024-03-20 00:19 UTC, juperameza approved these changes

2024-03-20 00:45 UTC, MauricioNC approved these changes

2024-03-20 01:13 UTC, GustavoHiguera approved these changes

2024-03-20 01:22 UTC, merged