Sprint 2/issue 19#places list screen design
BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final pull request #32
Opened 2024-03-20 00:23 UTC by ramondiaz21

# Description

What did you implemented/Why did you implemented this:

-I made the view where the places will be shown, all the interactive part. 
Responsive was added too.
It includes controller, view and the route.
I made several examples, to see how will work once the crud were done.

## Testing

-Just run the server, and enter in the /places/list route.

## Screenshots

![image](https://github.com/BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final/assets/26145239/df2a8e6e-b9d2-411f-9d97-6fd91c00a2d8)

2024-03-20 15:16 UTC, JuanequeX requested changes

2024-03-20 15:16 UTC, JuanequeX commented on app/assets/stylesheets/application.css
> +} */
Remove this commented code

2024-03-20 15:16 UTC, JuanequeX commented on app/assets/stylesheets/places.css
> +    align-items: center;
```suggestion
    align-items: center;
```

2024-03-20 15:16 UTC, JuanequeX commented on app/assets/stylesheets/places.css
> +    justify-content: center;
```suggestion
    justify-content: center;
```

2024-03-20 15:16 UTC, JuanequeX commented on app/assets/stylesheets/places.css
> +    padding: 8px;
in this case the `padding` applied is `8px` if is correct, remove the above line.

2024-03-20 15:16 UTC, JuanequeX commented on app/controllers/places_controller.rb
> +  end
```suggestion
  def list; end
```

2024-03-20 15:16 UTC, JuanequeX commented on app/views/layouts/application.html.erb
> +    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
Improvements can be made to the integration of Bootstrap by leveraging the impormaps of Rails to incorporate external libraries more effectively. Actually, my suggestion is to use the Rails approach.

2024-03-20 15:16 UTC, JuanequeX commented on app/views/layouts/application.html.erb
> +    <%= javascript_include_tag 'sliders.js', 'data-turbolinks-track': 'reload' %>
Look, this js tag can be deleted and integrated  this one or any other library how `swiper` through the impormaps

2024-03-20 23:23 UTC, juperameza requested changes

2024-03-20 23:23 UTC, juperameza commented on app/assets/javascript/sliders.js
> +}
In my humble opinion I think comments like this just bloat your code, I thinks it intuitive what the code does if not you should aim to improve your code rather than commenting

2024-03-20 23:23 UTC, juperameza commented on app/assets/stylesheets/places.css
> +  }
Se why are you commenting this ??

2024-03-20 23:40 UTC, MauricioNC requested changes

2024-03-20 23:40 UTC, MauricioNC commented on app/assets/config/manifest.js
> +//= link sliders.js
Add a new line at the end of your code

2024-03-21 01:26 UTC, MauricioNC approved these changes

2024-03-21 23:04 UTC, juperameza approved these changes

2024-03-21 23:42 UTC, AnaCarrizales approved these changes

2024-03-21 23:51 UTC, juperameza approved these changes

2024-03-21 23:52 UTC, JuanequeX approved these changes

2024-03-22 00:03 UTC, merged