Implementing Pagination and Filtering in Lists
BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final pull request #33
Opened 2024-03-20 02:10 UTC by ErikGmz

# Description

- Installed and properly configured Pagy gem for Accommodations lists.
- Implemented prototype filters for accommodations searching.
- Added TomSelect library to improve multiple options selection controls.
- Added RangeSlider library to implement double sliders controls.
- Renamed 'name' column to 'title' in Accommodation model (this to prevent errors when joining with Details model).

## Examples

Now it's possible to search for accommodations based on the following features:
- Hosts.
- Categories.
- Details.
- Title.
- Prices per day range.
- Ratings range.
- Bedrooms numbers range.
- Bathrooms numbers range.
- Beds numbers range.
- Max guests numbers range.
- Availability dates range.
- Address.

2024-03-20 03:13 UTC, MauricioNC requested changes

2024-03-20 03:13 UTC, MauricioNC commented on app/javascript/controllers/rangeslider_controller.js
> +    }
What about to modify this to:

```javascript
let range = [this.minValue, this.maxValue]

if (this.rangeValue !== undefined && this.rangeValue !== "") {
  range = this.rangeValue.split(",").map(number => parseInt(number)).sort((a, b) => a - b)
}
```

2024-03-20 03:13 UTC, MauricioNC commented on app/views/accommodations/_search_filter_form.html.erb
> +<% end %>
Add a new line at the end of your code

2024-03-20 03:42 UTC, ErikGmz commented on app/javascript/controllers/rangeslider_controller.js
> +    }
Fixed!

2024-03-20 03:42 UTC, ErikGmz commented on app/views/accommodations/_search_filter_form.html.erb
> +<% end %>
Fixed!

2024-03-20 03:50 UTC, MauricioNC approved these changes

2024-03-20 23:19 UTC, juperameza approved these changes

2024-03-22 23:48 UTC, STR1ND3R approved these changes

2024-03-22 23:50 UTC, DevLuis123 approved these changes

2024-03-23 21:41 UTC, merged