Visualization and Reservation of Accommodations
BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final pull request #38
Opened 2024-04-03 01:00 UTC by ErikGmz

# Description

- Added the corresponding reservations lists and filtering options.
- Reservations creations and modifications with the corresponding users, accommodations and reservations dates.
- Created new datepicker controller with non conflicting reservations validations.
- Added an option to delete accomodations.

## Testing

- Run either bin/dev or rails server commands and navigate to localhost:3000/reservations endpoint.

2024-04-03 01:03 UTC, AnaCarrizales approved these changes

2024-04-03 02:26 UTC, MauricioNC requested changes

2024-04-03 02:26 UTC, MauricioNC commented on app/models/accommodation.rb
> +    reservations.where(active: true).where.not(id: reservation_id).map(&:dates_range)
use `pluck(:dates_range)` instead of `map(&:dates_range)`
#
you can read more at:
- https://www.fastruby.io/blog/performance/rails/writing-fast-rails.html
- https://www.rubyinrails.com/2014/06/05/rails-pluck-vs-select-map-collect/

2024-04-03 02:26 UTC, MauricioNC commented on app/models/reservation.rb
> +  end
You could rewrite this as:

```ruby
def is_active?
  active
end
```
Do you need explicitly the "Yes" or "No" response?

2024-04-03 03:24 UTC, ErikGmz commented on app/controllers/accommodations_occupation_controller.rb
> +                    Accommodation.all.first
Fixed!

2024-04-03 03:24 UTC, ErikGmz commented on app/models/accommodation.rb
> +    reservations.where(active: true).where.not(id: reservation_id).map(&:dates_range)
Fixed!

2024-04-03 03:28 UTC, ErikGmz commented on app/models/reservation.rb
> +  end
That method is indeed intented to print either a "Yes" or "No" response depending on the active field value, so I changed its name in order to avoid more misundersandings.

2024-04-03 03:41 UTC, MauricioNC approved these changes

2024-04-05 00:35 UTC, juperameza approved these changes

2024-04-05 02:30 UTC, merged