Sprint 3/issue 34#reservations screen
BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final pull request #41
Opened 2024-04-09 00:00 UTC by ramondiaz21

-A view was created where the user will be able to visualize the reservations he/she has made, only his/her own, as well as other links of interest. 
-At the moment it does not have integrated logic, it is only the view.
-We added the responsiveness of the page so that it looks good on any device.

-You can see the view at the following url http://127.0.0.1:3000/reservations/
![image](https://github.com/BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final/assets/26145239/5a68abd4-26ee-4b08-89f5-9e84ebc866ee)
![image](https://github.com/BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final/assets/26145239/736add04-f68e-4168-bfaf-1a5bdc3161fa)

2024-04-09 00:14 UTC, MauricioNC requested changes

2024-04-09 00:14 UTC, MauricioNC commented on app/views/reservations/index.html.erb
> +</div>
Add a new empty line

2024-04-09 00:14 UTC, MauricioNC commented on app/views/reservations/index.html.erb
> +        </svg>
Use a partial for each svg instead of have all the code in the HTML, by this way you will keep your HTML code more readable and cleaner.

2024-04-10 00:02 UTC, MauricioNC approved these changes

2024-04-10 16:37 UTC, juperameza requested changes

2024-04-10 16:37 UTC, juperameza commented on app/assets/stylesheets/profile.css
> +      border-color 0.3s ease;
Order all your styles alphabetically

2024-04-10 16:37 UTC, juperameza commented on app/views/layouts/application.html.erb
> +  </script>
What  are you using jQuery for?

2024-04-10 16:37 UTC, juperameza commented on app/views/reservations/_button-filters.html.erb
> +
New line at the end of the file

2024-04-10 16:37 UTC, juperameza commented on app/views/reservations/_resources.html.erb
> + </div>
Same here new line
Also mind the usage of those divs 
You're using them a lot mind accessibility!!

2024-04-10 23:01 UTC, JuanequeX approved these changes

2024-04-10 23:36 UTC, juperameza approved these changes

2024-04-11 17:54 UTC, PudinDeveloper approved these changes

2024-04-19 04:18 UTC, merged