Users Management for Super Administrator
BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final pull request #44
Opened 2024-04-09 04:17 UTC by ErikGmz

# Description

- Added a users management system, which is a exclusive tool for the admin user.
- The admin is able to create new users, specifying information such as email, role and password.
- The admin can list and search all the registered users (except themself).
- The admin can modifiy any user data (except their password).
- The admin can delete any user.
- Minor fixes with images management in accommodations and users forms.

## Testing

- Run the rails db:migrate to properly create the database in a local PostgreSQL environment.
- Run the rails db:seed command in order to load all the default users data.
- Run either bin/dev or rails server and open the localhost:3000 endpoint in any browser.
- Login with the admintest@brightcoders.com email in order to check the users CRUD.

2024-04-09 04:32 UTC, MauricioNC approved these changes

2024-04-12 17:11 UTC, PudinDeveloper approved these changes

2024-04-15 23:33 UTC, juperameza requested changes

2024-04-15 23:33 UTC, juperameza commented on test/controllers/users_management_controller_test.rb
> +  # end
dont leave commented code

2024-04-15 23:43 UTC, MauricioNC approved these changes

2024-04-16 02:56 UTC, ErikGmz commented on test/controllers/users_management_controller_test.rb
> +  # end
Fixed!

2024-04-19 00:16 UTC, juperameza approved these changes

2024-04-19 04:12 UTC, merged