Added styling to Resend Verification Email Page &  Password Recovery …
BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final pull request #45
Opened 2024-04-10 00:10 UTC by STR1ND3R

2024-04-10 00:49 UTC, MauricioNC requested changes

2024-04-10 00:49 UTC, MauricioNC commented on app/views/users/confirmations/new.html.erb
> +</div>
Add an empty line at the end of your code

2024-04-10 00:49 UTC, MauricioNC commented on app/views/users/passwords/new.html.erb
> +</div>
Add an empty line at the end of your code

2024-04-10 01:02 UTC, STR1ND3R commented on app/views/users/confirmations/new.html.erb
> +</div>
done

2024-04-10 01:03 UTC, STR1ND3R commented on app/views/users/passwords/new.html.erb
> +</div>
done

2024-04-10 01:16 UTC, MauricioNC approved these changes

2024-04-10 16:15 UTC, JuanequeX approved these changes

2024-04-11 17:53 UTC, PudinDeveloper approved these changes

2024-04-11 22:52 UTC, merged