Sprint 5/issue 46#editing show and edit reservations screen
BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final pull request #49
Opened 2024-04-12 18:44 UTC by ramondiaz21

The view was created to be able to visualize individually each one of the reservations, as well as the view for the edition of each one of them.
The corresponding responsibility was added.
You can view the changes in the url http://127.0.0.1:3000/reservations/1
and at http://127.0.0.1:3000/reservations/1/edit
![screencapture-127-0-0-1-3000-reservations-1-2024-04-12-12_41_50](https://github.com/BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final/assets/26145239/3651fa5e-b8c1-40a3-a3cf-0473bbde535a)

![screencapture-127-0-0-1-3000-reservations-1-edit-2024-04-12-12_41_33](https://github.com/BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final/assets/26145239/528e4d31-6484-4c71-8047-b1b9360269ca)

2024-04-12 20:28 UTC, MauricioNC approved these changes

2024-04-12 20:28 UTC, MauricioNC commented on app/assets/stylesheets/application.tailwind.css
> +@import 'actiontext.css';
Add a new line at the end of your code

2024-04-12 20:28 UTC, MauricioNC commented on app/views/reservations/_form.html.erb
> +<% end %>
Add a new line at the end of your code

2024-04-12 20:28 UTC, MauricioNC commented on app/views/reservations/_reservation.html.erb
> +<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 gap-4">
Indent correctly this code

2024-04-12 20:28 UTC, MauricioNC commented on app/views/reservations/_form.html.erb
Indent correctly this code

2024-04-12 20:28 UTC, MauricioNC commented on app/views/reservations/edit.html.erb
> +    <% end %>
Same, indent correctly this code

2024-04-12 20:28 UTC, MauricioNC commented on app/views/users/sessions/new.html.erb
>    </div>
Remove empty line or move image_tag to the next line

2024-04-12 20:38 UTC, MauricioNC requested changes

2024-04-12 20:38 UTC, MauricioNC commented on app/assets/stylesheets/application.tailwind.css
> +@import 'actiontext.css';
Add a new line at the end of your code

2024-04-12 20:38 UTC, MauricioNC commented on app/views/reservations/_form.html.erb
> +  <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>
Indent correctly this code

2024-04-12 20:38 UTC, MauricioNC commented on app/views/reservations/_form.html.erb
> +<% end %>
Add a new line at the end of your code

2024-04-12 20:38 UTC, MauricioNC commented on app/views/reservations/_reservation.html.erb
> +<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 gap-4">
Indent correctly this code

2024-04-12 20:38 UTC, MauricioNC commented on app/views/reservations/_reservation.html.erb
> +      <% end %>
Indent correctly this code

2024-04-12 20:38 UTC, MauricioNC commented on app/views/reservations/edit.html.erb
> +    <% end %>
Same, indent correctly this code

2024-04-12 20:38 UTC, MauricioNC commented on app/views/reservations/edit.html.erb
> +    <% end %>
Same, indent correctly this code

2024-04-12 20:38 UTC, MauricioNC commented on app/views/users/sessions/new.html.erb
>    </div>
Remove empty line or move image_tag to the next line

2024-04-15 23:32 UTC, juperameza requested changes

2024-04-15 23:32 UTC, juperameza commented on app/views/reservations/_reservation.html.erb
> +      <% end %>
same here with the indentatio, i reccommend looking for a formatting extension i think prettier works just have to format it

2024-04-20 06:50 UTC, PudinDeveloper approved these changes
Fix the issues already mentioned and also...

Here are some extensions I use that could be quite helpful for some of the issues mentioned by other mentors:

- [Prettier - Code formatter](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)
- [Ruby Language Server](https://marketplace.visualstudio.com/items?itemName=Shopify.ruby-lsp)
- [Simple Ruby ERB](https://marketplace.visualstudio.com/items?itemName=vortizhe.simple-ruby-erb)
- [Trailing Spaces](https://marketplace.visualstudio.com/items?itemName=shardulm94.trailing-spaces)
- [Error Lens](https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens)
- [Path Intellisense](https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense)

2024-04-25 00:18 UTC, DevLuis123 commented on app/assets/stylesheets/application.tailwind.css
> +@import 'actiontext.css';
solved!

2024-04-25 00:19 UTC, DevLuis123 commented on app/assets/stylesheets/application.tailwind.css
> +@import 'actiontext.css';
done!

2024-04-25 00:28 UTC, DevLuis123 commented on app/views/reservations/_reservation.html.erb
> +      <% end %>
done!

2024-04-25 00:29 UTC, DevLuis123 commented on app/views/reservations/_form.html.erb
> +  <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>
done!

2024-04-25 00:30 UTC, DevLuis123 commented on app/views/reservations/edit.html.erb
> +    <% end %>
done!

2024-04-25 00:46 UTC, MauricioNC approved these changes

2024-04-25 01:08 UTC, juperameza approved these changes

2024-04-25 23:32 UTC, merged