Sprint 3/issue 30#home page
BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final pull request #52
Opened 2024-04-19 01:28 UTC by DevLuis123

![image](https://github.com/BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final/assets/114421767/ab52026a-a40b-4c59-8f14-a26e2b4b50b3)

2024-04-19 01:34 UTC, MauricioNC requested changes

2024-04-19 01:34 UTC, MauricioNC commented on .vscode/settings.json
> +{}
What is this file for?

2024-04-19 01:34 UTC, MauricioNC commented on app/assets/stylesheets/show_reservation.css
> +}
Add an empty line at the end of your code

2024-04-19 01:56 UTC, MauricioNC requested changes

2024-04-19 01:56 UTC, MauricioNC commented on app/views/reservations/_search_filter_form.html.erb
> +<% end %>
Add an empty line at the end of your code

2024-04-19 01:56 UTC, MauricioNC commented on app/views/reservations/index.html.erb
> +</div>
Add an empty line at the end of your code

2024-04-19 02:07 UTC, MauricioNC commented
This is a PR for a home page, nevertheless you are committing a lot of changes in different files. Remember that PRs must be small changes as well as their commits. 
It is too hard review all your code due to the quantity of changes, just keep this in mind for futures PRs.

Also you have many conflicts pending to resolve.

2024-04-19 06:27 UTC, PudinDeveloper approved these changes
Approved, only address the changes requested by others and I added some suggestions.

2024-04-19 06:27 UTC, PudinDeveloper commented on app/assets/stylesheets/home_page.css
Suggestion: Alphabetically order the CSS

2024-04-19 06:27 UTC, PudinDeveloper commented on app/assets/stylesheets/show_reservation.css
Suggestion: Alphabetically order the CSS

2024-04-20 00:31 UTC, DevLuis123 commented on .vscode/settings.json
> +{}
I don't know, but it has already been deleted!!

2024-04-20 00:35 UTC, DevLuis123 commented on app/views/reservations/index.html.erb
> +        <%= link_to "New reservation", new_reservation_path, class: "inline-block rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
okay! we will solve it later

2024-04-24 00:21 UTC, MauricioNC approved these changes

2024-04-24 00:22 UTC, AnaCarrizales approved these changes

2024-04-24 00:23 UTC, merged