Sprint 7/issue 55#add accommodation view style
BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final pull request #59
Opened 2024-04-27 03:14 UTC by farellano0

# What did you implement/Why did you implement this:

- I developed the style for the "View Accommodation" page by adapting the HTML and implementing new CSS classes aimed at enhancing the visual appeal and usability of the page. This effort included not just aesthetic improvements, but also functional enhancements to make the page more user-friendly.
- A partial was updated and standardized across all screens, now including a link to the route, ensuring seamless navigation and consistency in the user interface across the application. This partial implementation helps in reducing redundancy and improving maintainability.
- Along with these updates, a helper function was refined to support the new link functionality in the partial, making it more versatile and efficient in guiding users through the application's various pages.

## Testing
How you can test or look at the changes:

- Navigate to the "View Accommodation" page to assess the new styles and layout. The enhancements should be apparent in the improved layout and interactive elements.
- Test the functionality of the updated partial on different screens to ensure that the link to the route is working correctly and that the interface remains consistent across various parts of the application.

## Screenshots
![image](https://github.com/BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final/assets/73454963/ce06b47b-c70d-407c-9b7c-e742a1e31ff9)
![image](https://github.com/BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final/assets/73454963/7a252d1c-33cb-4349-a793-8a3704622f3a)

![image](https://github.com/BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final/assets/73454963/345aa57d-d979-41b8-9a6a-a15e6f35a80e)
![image](https://github.com/BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final/assets/73454963/f1c0792d-db79-4938-86ff-f1e45f5add53)
![image](https://github.com/BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final/assets/73454963/714bee0b-c8f4-4983-9c57-aafef1c285af)

2024-04-27 03:46 UTC, MauricioNC requested changes

2024-04-27 04:19 UTC, PudinDeveloper approved these changes

2024-04-30 00:23 UTC, farellano0 commented on app/helpers/application_helper.rb
> +    end
Done!

2024-04-30 00:30 UTC, MauricioNC approved these changes
LGTM!

Just resolve the conflicts

2024-04-30 01:07 UTC, juperameza commented on app/helpers/application_helper.rb
> +    end
Wouldn't it be neccesary an or at the end to take into account the rootpath if no key is there ? 
`navigation_path = controller_name_hashmap[controller_name.to_sym] || root_path`

2024-04-30 01:13 UTC, farellano0 commented on app/views/accommodations/show.html.erb
> +    <div class="">
Thanks for catching that! The empty class in the div was left over from earlier stages of development. I'll correct it.

2024-04-30 01:16 UTC, MauricioNC commented on app/helpers/application_helper.rb
> +    end
You're right, seems to be a good validation

2024-04-30 01:16 UTC, farellano0 commented
> Also what is the purpose of leaving the logitude and latitude for the user to see? I don't think the user gains someting by seeing that information

It can be particularly helpful for people who are using specialized map applications. Additionally, exact coordinates can give a precise location, which is useful for areas that are not well covered by street addresses or where addresses might be confusing.

2024-04-30 01:22 UTC, juperameza commented on app/helpers/application_helper.rb
> +    end
@farellano0

2024-04-30 01:37 UTC, merged