Sprint 6/issue 48#reservation screen
BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final pull request #62
Opened 2024-05-01 00:43 UTC by DevLuis123

redesign of the reservation screen, and edit reseration

2024-05-01 00:47 UTC, MauricioNC requested changes

2024-05-01 00:47 UTC, MauricioNC commented on app/assets/stylesheets/application.css
> +}
add an empty line at the end of your code

2024-05-01 00:47 UTC, MauricioNC commented on app/assets/stylesheets/new_reservation.css
> +  }
add an empty line at the end of your code

2024-05-01 00:47 UTC, MauricioNC commented on app/views/reservations/_search_filter_form.html.erb
> +<% end %>
add an empty line at the end of your code

2024-05-01 06:23 UTC, PudinDeveloper approved these changes
Try to order the CSS alphabetically and solve the other issues mentioned.

2024-05-02 23:14 UTC, DevLuis123 commented on app/assets/stylesheets/application.css
> +}
done!

2024-05-02 23:15 UTC, DevLuis123 commented on app/assets/stylesheets/new_reservation.css
> +  }
done!

2024-05-02 23:15 UTC, DevLuis123 commented on app/views/reservations/_search_filter_form.html.erb
> +<% end %>
done!

2024-05-02 23:34 UTC, MauricioNC requested changes

2024-05-02 23:34 UTC, MauricioNC commented on app/assets/stylesheets/new_reservation.css
> +
Add an empty line at the end of your code

2024-05-02 23:35 UTC, MauricioNC approved these changes

2024-05-02 23:41 UTC, STR1ND3R approved these changes

2024-05-04 01:51 UTC, merged