Sprint 7/issue 61#bug home page
BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final pull request #68
Opened 2024-05-07 00:10 UTC by DevLuis123

carousel error in index fixed

2024-05-07 06:00 UTC, PudinDeveloper approved these changes

2024-05-07 16:52 UTC, MauricioNC requested changes

2024-05-07 16:52 UTC, MauricioNC commented on app/views/home/index.html.erb
> +    <div class="carrusel">
Did you mean carousel?

2024-05-07 16:52 UTC, MauricioNC commented on app/assets/stylesheets/home_page.css
>  .carrusel {
Did you mean carousel?

2024-05-07 16:52 UTC, MauricioNC commented on app/views/profiles/show.html.erb
>          <%= link_to 'Edit Profile', edit_profile_path, class:"mr-7" %>
Is this indentation size same as others?

2024-05-08 00:25 UTC, DevLuis123 commented on app/views/home/index.html.erb
> +    <div class="carrusel">
I have fixed it, sorry!!

2024-05-08 00:25 UTC, DevLuis123 commented on app/assets/stylesheets/home_page.css
>  .carrusel {
same!!

2024-05-08 00:29 UTC, DevLuis123 commented on app/views/profiles/show.html.erb
>          <%= link_to 'Edit Profile', edit_profile_path, class:"mr-7" %>
no, it isn't, but its fixed

2024-05-08 01:01 UTC, MauricioNC commented on app/assets/stylesheets/home_page.css
>  .carrusel {
Are you sure? I just see the same code

2024-05-08 01:22 UTC, MauricioNC approved these changes

2024-05-08 01:32 UTC, STR1ND3R approved these changes

2024-05-08 01:33 UTC, merged