Improve blogs style
BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final pull request #70
Opened 2024-05-07 01:23 UTC by farellano0

# Description
## What did I implement/Why did I implement this:

- **What?:** I've updated the filter styles and added new methods in application_helper, alongside enhancing the styling for Posts.
- **Why?:** These changes aim to make the filter options more intuitive and visually appealing, which enhances user experience. The addition of methods in application_helper is intended to streamline backend processes for better performance and maintenance.

## Screenshots
![image](https://github.com/BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final/assets/73454963/9bf19d53-2cad-4054-9956-0a62ee68309f)
![image](https://github.com/BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final/assets/73454963/eec8de77-f14e-44d1-a1fa-f25d017c0ea3)

2024-05-07 03:48 UTC, MauricioNC requested changes

2024-05-07 03:48 UTC, MauricioNC commented on app/views/posts/index.html.erb
> +  <div class="filtro mb-4">
Change this class to English

2024-05-07 05:48 UTC, PudinDeveloper approved these changes
Don't forget to alphabetize the CSS classes

2024-05-07 06:24 UTC, juperameza reviewed
kudos on the helper
But order all your styles alphabetically 
And out of context
Stop filling roles in valorant stick to a role 🗣️🗣️

2024-05-07 06:24 UTC, juperameza commented on app/helpers/application_helper.rb
> +  end
Doesn't this work 
https://apidock.com/rails/String/truncate

2024-05-07 06:24 UTC, juperameza commented on app/assets/stylesheets/application.css
>    margin-left: 10px;
Order alphabetical

2024-05-07 06:24 UTC, juperameza commented on app/assets/stylesheets/filter.css
> +  border-radius: 25px;
Alphabetical order

2024-05-07 06:24 UTC, juperameza commented on app/assets/stylesheets/posts.css
> +  transition: transform 0.3s ease, box-shadow 0.3s ease;
Order this alphabetically

2024-05-07 06:25 UTC, juperameza requested changes
Lol didn't push on ask for changes

2024-05-08 01:15 UTC, farellano0 commented on app/assets/stylesheets/application.css
>    margin-left: 10px;
Done!

2024-05-08 01:16 UTC, farellano0 commented on app/assets/stylesheets/posts.css
> +  transition: transform 0.3s ease, box-shadow 0.3s ease;
Done!

2024-05-08 01:17 UTC, farellano0 commented on app/views/posts/index.html.erb
> +  <div class="filtro mb-4">
Done!

2024-05-08 01:20 UTC, MauricioNC commented on app/views/posts/index.html.erb
> +  <div class="filtro mb-4">
I'm still seeing the same class in Spanish

2024-05-08 01:29 UTC, farellano0 commented on app/helpers/application_helper.rb
> +  end
Done!

2024-05-08 01:29 UTC, farellano0 commented on app/assets/stylesheets/application.css
>    margin-left: 10px;
Done!

2024-05-08 01:30 UTC, farellano0 commented on app/assets/stylesheets/filter.css
> +  border-radius: 25px;
Done!

2024-05-08 01:34 UTC, juperameza approved these changes

2024-05-08 02:07 UTC, MauricioNC requested changes

2024-05-08 02:07 UTC, MauricioNC commented on app/assets/stylesheets/home_page.css
> +.degradado {
Change this class selector to English

2024-05-08 02:07 UTC, MauricioNC commented on app/assets/stylesheets/home_page.css
> +.carrusel {
Also you still have this class selector in Spanish, change it to English

2024-05-08 06:21 UTC, PudinDeveloper approved these changes

2024-05-08 23:38 UTC, farellano0 commented on app/assets/stylesheets/home_page.css
> +.degradado {
Done!

2024-05-08 23:39 UTC, farellano0 commented on app/assets/stylesheets/home_page.css
> +.carrusel {
Done!

2024-05-08 23:48 UTC, MauricioNC approved these changes

2024-05-09 00:02 UTC, merged