Users' Favorite Posts System
BrightCoders-Institute/s10a1-proyecto-final-team-01-s10a1-proyecto-final pull request #77
Opened 2024-05-10 02:19 UTC by ErikGmz

# Description

- Added an option in order to allow all the users to mark any posts as their favorites.
- Added a filter in posts index in order to only show the user's currently favorite posts.

## Testing

- Run the rails db:migrate to properly create the database in a local PostgreSQL environment.
- Install Action Text and Active Storage.
- Run the rails db:seed command in order to load all the default users data.
- Run either bin/dev or rails server and open the localhost:3000 endpoint in any browser.
- Login with any account in order to check the new posts' features.

2024-05-10 02:58 UTC, MauricioNC approved these changes

2024-05-10 03:37 UTC, PudinDeveloper requested changes

2024-05-10 03:37 UTC, PudinDeveloper commented on test/models/favorite_post_test.rb
> +  # end
Remove these lines -- commit this suggestion please 👍🏼 

```suggestion
```

2024-05-10 04:19 UTC, PudinDeveloper approved these changes
Thanks! LGTM

2024-05-14 00:31 UTC, AnaCarrizales approved these changes

2024-05-14 05:55 UTC, merged